server:
  port: 7001

eureka:
  instance:
    hostname: eureka-7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #集群指向其它eureka
#      defaultZone: http://eureka-7002.com:7002/eureka/
      #单机就指向7001自己
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #server:
    #enable-self-preservation: false # 关闭自我保护模式（默认开启）
    #eviction-interval-timer-in-ms: 2000  # 等待时间2秒钟（默认60秒 两秒没有连上直接注销）
