server:
  port: 8006

spring:
  application:
    name: consul-provider-server
  cloud:
    # consul注册中心地址
    consul:
      host: 192.168.25.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}